---
title: "female-birth-rate"
author: "Hae Kyung Im"
date: "2020-01-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## proportion of female birth

We are told that 241,945 girls and 251,527 boys were born in Paris from 1745 to 1770.

```{r data}

y = 241945
n = 241945 + 251527

```


```{r unnormalized, echo=FALSE, eval=FALSE}

unnorm_posterior2 = function(theta) {exp( y*log(theta) + (n-y)*log((1 - theta)) )}

curve(unnorm_posterior2,from = 0,to = 1, main=paste("n = ",n,";  y = ",y),xlab="theta",ylab='unnorm_posterior')

print("the unnormalized density and the normalizing factors are too small and lead to numerical errors")

```

```{r normalized}

posterior = function(theta) dbeta(theta,shape1 = y+1, shape2 = n- y + 1)
curve(posterior,from = 0,to = 1, main=paste("n = ",n,";  y = ",y),xlab="theta",ylab='posterior')

```

```{r zoom in}
curve(posterior,from = 0.485,to = 0.495, main=paste("n = ",n,";  y = ",y),xlab="theta",ylab='posterior')
```

```{r zoom in and mle shown}
curve(posterior,from = 0.485,to = 0.495, main=paste("n = ",n,";  y = ",y, "; mle shown in gray"),xlab="theta",ylab='posterior')
abline(v=y/n,col='gray')
```
